"use strict";

const FAILURE_CODES = Object.freeze({
  TIMEOUT: "TIMEOUT",
  RATE_LIMITED: "RATE_LIMITED",
  AUTH_ERROR: "AUTH_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  CONTENT_REJECTED: "CONTENT_REJECTED",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN_PROVIDER_ERROR: "UNKNOWN_PROVIDER_ERROR"
});

module.exports = {
  FAILURE_CODES
};
